version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application
    ports:
      - "5432:5432"

  flask-server:
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
